In [1]:
import urllib
from urllib.request import urlopen
import pandas as pd
import numpy as np

In [2]:
def make_soup(url):
    req = urllib.request.Request(url, 
    headers={'User-Agent': 'Mozilla/5.0'})
    webpage = urlopen(req)
    main_doc = webpage.read()
    return main_doc

In [3]:

years = [2010, 2011, 2012, 2013 ,2014 ,2015 ,2016 ,2017, 2018, 2019, 2020, 2021]
df_list=[]

#get draft data from 2010-2021
for year in years:
    #print(team)
    try:
        soup= make_soup("https://www.basketball-reference.com/draft/NBA_"+str(year)+".html/")
        df_list.append(pd.read_html(soup)[0])
    except Exception as e:
            pass

In [4]:
#store data in df
df = pd.concat(df_list)

In [25]:
df.head()

,Rk,Pk,Tm,Player,College,Yrs,G,MP,PTS,TRB,...,3P%,FT%,MP,PTS,TRB,AST,WS,WS_48,BPM,VORP
0,1,1,WAS,john wall,Kentucky,10,613,21833,11702,2612,...,.323,.779,35.6,19.1,4.3,9.1,44.1,.097,2.4,24.0
1,2,2,PHI,evan turner,Ohio State,10,705,18938,6824,3278,...,.294,.782,26.9,9.7,4.6,3.5,20.2,.051,-1.9,0.5
2,3,3,NJN,derrick favors,Georgia Tech,12,790,19202,8354,5608,...,.198,.663,24.3,10.6,7.1,1.1,60.3,.151,0.9,14.0
3,4,4,MIN,wesley johnson,Syracuse,9,609,13472,4235,1924,...,.337,.741,22.1,7.0,3.2,1.1,10.7,.038,-1.6,1.2
4,5,5,SAC,demarcus cousins,Kentucky,11,652,19481,12784,6655,...,.330,.737,29.9,19.6,10.2,3.0,46.6,.115,2.4,21.6

In [58]:

colnames=["Rk",	"Pk",	"Tm",	"Player",	"College"	,"Yrs",	"G"	,"MP",	"PTS",	"TRB",	"AST",	"FG%",
	"3P%",	"FT%"	,"MP"	,"PTS",	"TRB",	"AST",	"WS",	"WS_48",	"BPM",	"VORP"]

In [19]:
#change column names
df.columns = colnames

In [26]:
df.head()

,Rk,Pk,Tm,Player,College,Yrs,G,MP,PTS,TRB,...,3P%,FT%,MP,PTS,TRB,AST,WS,WS_48,BPM,VORP
0,1,1,WAS,john wall,Kentucky,10,613,21833,11702,2612,...,.323,.779,35.6,19.1,4.3,9.1,44.1,.097,2.4,24.0
1,2,2,PHI,evan turner,Ohio State,10,705,18938,6824,3278,...,.294,.782,26.9,9.7,4.6,3.5,20.2,.051,-1.9,0.5
2,3,3,NJN,derrick favors,Georgia Tech,12,790,19202,8354,5608,...,.198,.663,24.3,10.6,7.1,1.1,60.3,.151,0.9,14.0
3,4,4,MIN,wesley johnson,Syracuse,9,609,13472,4235,1924,...,.337,.741,22.1,7.0,3.2,1.1,10.7,.038,-1.6,1.2
4,5,5,SAC,demarcus cousins,Kentucky,11,652,19481,12784,6655,...,.330,.737,29.9,19.6,10.2,3.0,46.6,.115,2.4,21.6

In [21]:
#create a list from Player column
players = df['Player'].tolist()

In [34]:
#add hypen to each player (names include hypen in URL)
player_list = list(map(lambda x: x.replace(' ', '-'), players))

In [38]:
#convert names to lowercase
player_list = list(map(lambda x: x.lower(), player_list))

In [ ]:
#player_list

In [82]:
df_list2=[]
#get college stats for players in NBA draft, each have own URL
for player in player_list:
    #print(player)
    try:
        soup= make_soup("https://www.sports-reference.com/cbb/players/"+player+"-1.html")
        temp_df=pd.read_html(soup)[0]
        temp_df["name"] = player #add player name to dataframe
        df_list2.append(temp_df)
    except Exception as e:
            pass

john-wall
evan-turner
derrick-favors
wesley-johnson
demarcus-cousins
ekpe-udoh
greg-monroe
al-farouq-aminu
gordon-hayward
paul-george
cole-aldrich
xavier-henry
ed-davis
patrick-patterson
larry-sanders
luke-babbitt
kevin-séraphin
eric-bledsoe
avery-bradley
james-anderson
craig-brackins
elliot-williams
trevor-booker
damion-james
dominique-jones
quincy-pondexter
jordan-crawford
greivis-vásquez
daniel-orton
lazar-hayward
round-2
player
tibor-pleiß
dexter-pittman
hassan-whiteside
armon-johnson
nemanja-bjelica
terrico-white
darington-hobson
andy-rautins
landry-fields
lance-stephenson
jarvis-varnado
da'sean-butler
devin-ebanks
jerome-jordan
paulão-prestes
gani-lawal
tiny-gallon
latavious-williams
ryan-richards
solomon-alabi
magnum-rolle
luke-harangody
pape-sy
willie-warren
jeremy-evans
hamady-n'diaye
ryan-reid
derrick-caracter
stanley-robinson
dwayne-collins
kyrie-irving
derrick-williams
enes-freedom
tristan-thompson
jonas-valančiūnas
jan-veselý
bismack-biyombo
brandon-knight
kemba-walker
jimmer-fredette
klay-thompson
alec-burks
markieff-morris
marcus-morris
kawhi-leonard
nikola-vučević
iman-shumpert
chris-singleton
tobias-harris
donatas-motiejūnas
nolan-smith
kenneth-faried
nikola-mirotić
reggie-jackson
marshon-brooks
jordan-hamilton
jajuan-johnson
norris-cole
cory-joseph
jimmy-butler
round-2
player
bojan-bogdanović
justin-harper
kyle-singler
shelvin-mack
tyler-honeycutt
jordan-williams
trey-thompkins
chandler-parsons
jeremy-tyler
jon-leuer
darius-morris
dāvis-bertāns
malcolm-lee
charles-jenkins
josh-harrellson
andrew-goudelock
travis-leslie
keith-benson
josh-selby
lavoy-allen
jon-diebler
vernon-macklin
deandre-liggins
milan-mačvan
e'twaun-moore
chukwudiebere-maduabum
tanguy-ngombo
ater-majok
ádám-hanga
isaiah-thomas
anthony-davis
michael-kidd-gilchrist
bradley-beal
dion-waiters
thomas-robinson
damian-lillard
harrison-barnes
terrence-ross
andre-drummond
austin-rivers
meyers-leonard
jeremy-lamb
kendall-marshall
john-henson
maurice-harkless
royce-white
tyler-zeller
terrence-jones
andrew-nicholson
evan-fournier
jared-sullinger
fab-melo
john-jenkins
jared-cunningham
tony-wroten
miles-plumlee
arnett-moultrie
perry-jones
marquis-teague
festus-ezeli
round-2
player
jeff-taylor
tomáš-satoranský
bernard-james
jae-crowder
draymond-green
orlando-johnson
quincy-acy
quincy-miller
khris-middleton
will-barton
tyshawn-taylor
doron-lamb
mike-scott
kim-english
justin-hamilton
darius-miller
kevin-murphy
kostas-papanikolaou
kyle-o'quinn
i̇zzet-türkyılmaz
kris-joseph
ognjen-kuzmić
furkan-aldemir
tornike-shengelia
darius-johnson-odom
tomislav-zubčić
i̇lkan-karaman
robbie-hummel
marcus-denmon
robert-sacre
anthony-bennett
victor-oladipo
otto-porter-jr.
cody-zeller
alex-len
nerlens-noel
ben-mclemore
kentavious-caldwell-pope
trey-burke
cj-mccollum
michael-carter-williams
steven-adams
kelly-olynyk
shabazz-muhammad
giannis-antetokounmpo
lucas-nogueira
dennis-schröder
shane-larkin
sergey-karasev
tony-snell
gorgui-dieng
mason-plumlee
solomon-hill
tim-hardaway-jr.
reggie-bullock
andre-roberson
rudy-gobert
livio-jean-charles
archie-goodwin
nemanja-nedović
round-2
player
allen-crabbe
álex-abrines
carrick-felix
isaiah-canaan
glen-rice-jr.
ray-mccallum
tony-mitchell
nate-wolters
jeff-withey
grant-jerrett
jamaal-franklin
pierre-jackson
ricky-ledo
mike-muscala
marko-todorović
erick-green
raul-neto
ryan-kelly
erik-murphy
james-ennis-iii
romero-osby
lorenzo-brown
colton-iverson
arsalan-kazemi
joffrey-lauvergne
peyton-siva
alex-oriakhi
deshaun-thomas
bojan-dubljević
jānis-timma
andrew-wiggins
jabari-parker
joel-embiid
aaron-gordon
dante-exum
marcus-smart
julius-randle
nik-stauskas
noah-vonleh
elfrid-payton
doug-mcdermott
dario-šarić
zach-lavine
t.j.-warren
adreian-payne
jusuf-nurkić
james-young
tyler-ennis
gary-harris
bruno-caboclo
mitch-mcgary
jordan-adams
rodney-hood
shabazz-napier
clint-capela
p.j.-hairston
bogdan-bogdanović
c.j.-wilcox
josh-huestis
kyle-anderson
round-2
player
damien-inglis
k.j.-mcdaniels
joe-harris
cleanthony-early
jarnell-stokes
johnny-o'bryant
deandre-daniels
spencer-dinwiddie
jerami-grant
glenn-robinson-iii
nikola-jokić
nick-johnson
edy-tavares
markel-brown
dwight-powell
jordan-clarkson
russ-smith
lamar-patterson
cameron-bairstow
alec-brown
thanasis-antetokounmpo
vasilije-micić
alessandro-gentile
nemanja-dangubić
semaj-christon
devyn-marble
louis-labeyrie
jordan-mcrae
xavier-thames
cory-jefferson
karl-anthony-towns
d'angelo-russell
jahlil-okafor
kristaps-porziņģis
mario-hezonja
willie-cauley-stein
emmanuel-mudiay
stanley-johnson
frank-kaminsky
justise-winslow
myles-turner
trey-lyles
devin-booker
cameron-payne
kelly-oubre-jr.
terry-rozier
rashad-vaughn
sam-dekker
jerian-grant
delon-wright
justin-anderson
bobby-portis
rondae-hollis-jefferson
tyus-jones
jarell-martin
nikola-milutinov
larry-nance-jr.
r.j.-hunter
chris-mccullough
kevon-looney
round-2
player
cedi-osman
montrezl-harrell
jordan-mickey
anthony-brown
willy-hernangómez
rakeem-christmas
richaun-holmes
darrun-hilliard
juan-pablo-vaulet
josh-richardson
pat-connaughton
olivier-hanlan
joe-young
andrew-harrison
marcus-thornton
norman-powell
artūras-gudaitis
dakari-johnson
aaron-white
marcus-eriksson
tyler-harvey
satnam-singh
sir'dominic-pointer
dani-díez
cady-lalanne
branden-dawson
nikola-radičević
j.p.-tokoto
dimitrios-agravanis
luka-mitrović
ben-simmons
brandon-ingram
jaylen-brown
dragan-bender
kris-dunn
buddy-hield
jamal-murray
marquese-chriss
jakob-poeltl
thon-maker
domantas-sabonis
taurean-prince
georgios-papagiannis
denzel-valentine
juancho-hernangómez
guerschon-yabusele
wade-baldwin
henry-ellenson
malik-beasley
caris-levert
deandre'-bembry
malachi-richardson
ante-žižić
timothé-luwawu-cabarrot
brice-johnson
furkan-korkmaz
pascal-siakam
skal-labissière
dejounte-murray
damian-jones
round-2
player
deyonta-davis
ivica-zubac
cheick-diallo
tyler-ulis
rade-zagorac
malcolm-brogdon
chinanu-onuaku
patrick-mccaw
david-michineau
diamond-stone
stephen-zimmerman
isaiah-whitehead
zhou-qi
isaïa-cordinier
demetrius-jackson
a.j.-hammons
jake-layman
paul-zipser
michael-gbinije
georges-niang
ben-bentil
joel-bolomboy
petr-cornelie
kay-felder
marcus-paige
daniel-hamilton
wang-zhelin
abdel-nader
isaiah-cousins
tyrone-wallace
markelle-fultz
lonzo-ball
jayson-tatum
josh-jackson
de'aaron-fox
jonathan-isaac
lauri-markkanen
frank-ntilikina
dennis-smith-jr.
zach-collins
malik-monk
luke-kennard
donovan-mitchell
bam-adebayo
justin-jackson
justin-patton
d.j.-wilson
t.j.-leaf
john-collins
harry-giles
terrance-ferguson
jarrett-allen
og-anunoby
tyler-lydon
anžejs-pasečņiks
caleb-swanigan
kyle-kuzma
tony-bradley
derrick-white
josh-hart
round-2
player
frank-jackson
davon-reed
wes-iwundu
frank-mason-iii
ivan-rabb
jonah-bolden
semi-ojeleye
jordan-bell
jawun-evans
dwayne-bacon
tyler-dorsey
thomas-bryant
isaiah-hartenstein
damyean-dotson
dillon-brooks
sterling-brown
ike-anigbogu
sindarius-thornwell
vlatko-čančar
mathias-lessort
monte-morris
edmond-sumner
kadeem-allen
alec-peters
nigel-williams-goss
jabari-bird
sasha-vezenkov
ognjen-jaramaz
jaron-blossomgame
alpha-kaba
deandre-ayton
marvin-bagley-iii
luka-dončić
jaren-jackson-jr.
trae-young
mo-bamba
wendell-carter-jr.
collin-sexton
kevin-knox
mikal-bridges
shai-gilgeous-alexander
miles-bridges
jerome-robinson
michael-porter-jr.
troy-brown-jr.
zhaire-smith
donte-divincenzo
lonnie-walker-iv
kevin-huerter
josh-okogie
grayson-allen
chandler-hutchison
aaron-holiday
anfernee-simons
moritz-wagner
landry-shamet
robert-williams
jacob-evans
džanan-musa
omari-spellman
round-2
player
elie-okobo
jevon-carter
jalen-brunson
devonte'-graham
melvin-frazier
mitchell-robinson
gary-trent-jr.
khyri-thomas
isaac-bonga
rodions-kurucs
jarred-vanderbilt
bruce-brown
justin-jackson
issuf-sanon
hamidou-diallo
de'anthony-melton
svi-mykhailiuk
keita-bates-diop
chimezie-metu
alize-johnson
tony-carr
vince-edwards
devon-hall
shake-milton
arnoldas-kulboka
ray-spalding
kevin-hervey
thomas-welsh
george-king
kostas-antetokounmpo
zion-williamson
ja-morant
rj-barrett
de'andre-hunter
darius-garland
jarrett-culver
coby-white
jaxson-hayes
rui-hachimura
cam-reddish
cameron-johnson
p.j.-washington
tyler-herro
romeo-langford
sekou-doumbouya
chuma-okeke
nickeil-alexander-walker
goga-bitadze
luka-šamanić
matisse-thybulle
brandon-clarke
grant-williams
darius-bazley
ty-jerome
nassir-little
dylan-windler
mfiondu-kabengele
jordan-poole
keldon-johnson
kevin-porter-jr.
round-2
player
nic-claxton
kz-okpala
carsen-edwards
bruno-fernando
didi-louzada
cody-martin
deividas-sirvydis
daniel-gafford
alen-smailagić
justin-james
eric-paschall
admiral-schofield
jaylen-nowell
bol-bol
isaiah-roby
talen-horton-tucker
ignas-brazdeikis
terance-mann
quinndary-weatherspoon
jarrell-brantley
tremont-waters
jalen-mcdaniels
justin-wright-foreman
marial-shayok
kyle-guy
jaylen-hands
jordan-bone
miye-oni
dewan-hernandez
vanja-marinković
anthony-edwards
james-wiseman
lamelo-ball
patrick-williams
isaac-okoro
onyeka-okongwu
killian-hayes
obi-toppin
deni-avdija
jalen-smith
devin-vassell
tyrese-haliburton
kira-lewis-jr.
aaron-nesmith
cole-anthony
isaiah-stewart
aleksej-pokusevski
josh-green
saddiq-bey
precious-achiuwa
tyrese-maxey
zeke-nnaji
leandro-bolmaro
r.j.-hampton
immanuel-quickley
payton-pritchard
udoka-azubuike
jaden-mcdaniels
malachi-flynn
desmond-bane
round-2
player
tyrell-terry
vernon-carey-jr.
daniel-oturu
théo-maledon
xavier-tillman-sr.
tyler-bey
vit-krejci
saben-lee
elijah-hughes
robert-woodard-ii
tre-jones
nick-richards
jahmi'us-ramsey
marko-simonovic
jordan-nwora
cj-elleby
yam-madar
nico-mannion
isaiah-joe
skylar-mays
justinian-jessup
kenyon-martin-jr.
cassius-winston
cassius-stanley
jay-scrubb
grant-riller
reggie-perry
paul-reed
jalen-harris
sam-merrill
cade-cunningham
jalen-green
evan-mobley
scottie-barnes
jalen-suggs
josh-giddey
jonathan-kuminga
franz-wagner
davion-mitchell
ziaire-williams
james-bouknight
joshua-primo
chris-duarte
moses-moody
corey-kispert
alperen-şengün
trey-murphy-iii
tre-mann
kai-jones
jalen-johnson
keon-johnson
isaiah-jackson
usman-garuba
josh-christopher
quentin-grimes
bones-hyland
cam-thomas
jaden-springer
day'ron-sharpe
santi-aldama
round-2
player
isaiah-todd
jeremiah-robinson-earl
jason-preston
rokas-jokubaitis
herbert-jones
miles-mcbride
jt-thor
ayo-dosunmu
neemias-queta
jared-butler
joe-wieskamp
isaiah-livers
greg-brown-iii
kessler-edwards
juhann-begarin
dalano-banton
david-johnson
sharife-cooper
marcus-zegarowski
filip-petrušev
brandon-boston-jr.
luka-garza
charles-bassey
sandro-mamukelashvili
aaron-wiggins
scottie-lewis
balša-koprivica
jericho-sims
raiquan-gray
georgios-kalaitzakis

In [83]:
#store in dataframe
college = pd.concat(df_list2)

In [85]:
#college.to_csv("college.csv",index=False)

In [99]:
#college = pd.read_csv("college.csv")

In [100]:
college.head()

,Season,School,Conf,G,GS,MP,FG,FGA,FG%,2P,...,AST,STL,BLK,TOV,PF,PTS,Unnamed: 27,SOS,name,Unnamed: 25
0,2009-10,Kentucky,SEC,37,37,34.8,5.5,11.8,0.461,4.5,...,6.5,1.8,0.5,4.0,1.9,16.6,NaN,6.82,john-wall,NaN
1,Career,Kentucky,NaN,37,37,34.8,5.5,11.8,0.461,4.5,...,6.5,1.8,0.5,4.0,1.9,16.6,NaN,6.82,john-wall,NaN
2,2007-08,Ohio State,Big Ten,37,30,27.1,2.9,6.3,0.47,2.3,...,2.6,1.3,0.5,2.7,2.4,8.5,NaN,7.97,evan-turner,NaN
3,2008-09,Ohio State,Big Ten,33,33,36.4,5.8,11.6,0.503,5.5,...,4.0,1.8,0.8,3.5,2.9,17.3,NaN,8.23,evan-turner,NaN
4,2009-10,Ohio State,Big Ten,31,31,35.7,7.6,14.7,0.519,7.0,...,6.0,1.7,0.9,4.4,2.8,20.4,NaN,7.37,evan-turner,NaN

In [101]:
#remove hypen from name
college['name'] = college['name'].str.replace('-', ' ')

In [ ]:
#convert names in draft df to lower case so we can join it with college dataframe
df['Player'] = df['Player'].str.lower()

In [37]:
#inner join draft dataframe with college dataframe on the college and player name 
#add _college suffix to college variables to avoid duplicate variable names
df =  df.merge(college, left_on=["Player","College"], right_on=["name","School"], how='inner',suffixes=('','_college'))

In [60]:
#get rid of NBA stats 
df.drop(['Tm',
 'Player',
 'College',
 'Yrs',
 'G',
 'MP',
 'PTS',
 'TRB',
 'AST',
 'FG%',
 '3P%',
 'FT%',
 'MP',
 'PTS',
 'TRB',
 'AST',
 'WS',
 'WS_48',
 'BPM',
 'VORP'],inplace=True,axis=1)

In [62]:
df.head(10)

,Rk,Pk,Season,School,Conf,G_college,GS,MP_college,FG,FGA,...,AST_college,STL,BLK,TOV,PF,PTS_college,Unnamed: 27,SOS,name,Unnamed: 25
0,1,1,2009-10,Kentucky,SEC,37,37,34.8,5.5,11.8,...,6.5,1.8,0.5,4.0,1.9,16.6,NaN,6.82,john wall,NaN
1,1,1,Career,Kentucky,NaN,37,37,34.8,5.5,11.8,...,6.5,1.8,0.5,4.0,1.9,16.6,NaN,6.82,john wall,NaN
2,2,2,2007-08,Ohio State,Big Ten,37,30,27.1,2.9,6.3,...,2.6,1.3,0.5,2.7,2.4,8.5,NaN,7.97,evan turner,NaN
3,2,2,2008-09,Ohio State,Big Ten,33,33,36.4,5.8,11.6,...,4.0,1.8,0.8,3.5,2.9,17.3,NaN,8.23,evan turner,NaN
4,2,2,2009-10,Ohio State,Big Ten,31,31,35.7,7.6,14.7,...,6.0,1.7,0.9,4.4,2.8,20.4,NaN,7.37,evan turner,NaN
5,2,2,Career,Ohio State,NaN,101,94,32.8,5.3,10.6,...,4.1,1.6,0.7,3.5,2.7,15.0,NaN,7.86,evan turner,NaN
6,3,3,2009-10,Georgia Tech,ACC,36,35,27.5,5.0,8.1,...,1.0,0.9,2.1,2.5,2.6,12.4,NaN,9.02,derrick favors,NaN
7,3,3,Career,Georgia Tech,NaN,36,35,27.5,5.0,8.1,...,1.0,0.9,2.1,2.5,2.6,12.4,NaN,9.02,derrick favors,NaN
8,5,5,2009-10,Kentucky,SEC,38,37,23.5,5.4,9.7,...,1.0,1.0,1.8,2.1,3.2,15.1,NaN,6.82,demarcus cousins,NaN
9,5,5,Career,Kentucky,NaN,38,37,23.5,5.4,9.7,...,1.0,1.0,1.8,2.1,3.2,15.1,NaN,6.82,demarcus cousins,NaN

In [63]:
#keep only career college stats
#remove individual seasons  
df_clean = df[df['Season'] == "Career"]

In [66]:
df_clean.columns

Index(['Rk', 'Pk', 'Season', 'School', 'Conf', 'G_college', 'GS', 'MP_college',
       'FG', 'FGA', 'FG%_college', '2P', '2PA', '2P%', '3P', '3PA',
       '3P%_college', 'FT', 'FTA', 'FT%_college', 'ORB', 'DRB', 'TRB_college',
       'AST_college', 'STL', 'BLK', 'TOV', 'PF', 'PTS_college', 'Unnamed: 27',
       'SOS', 'name', 'Unnamed: 25'],
      dtype='object')

In [67]:
college.columns

Index(['Season', 'School', 'Conf', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '2P',
       '2PA', '2P%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB',
       'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Unnamed: 27', 'SOS',
       'name', 'Unnamed: 25'],
      dtype='object')

In [69]:
#drop unwanted cols
df_clean.drop(["Conf",'Unnamed: 27','Unnamed: 25'],inplace=True,axis=1)

/Users/jackpiccione/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4908: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [71]:
df_clean.drop("Season",inplace=True,axis=1)

/Users/jackpiccione/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4908: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [73]:
df_clean.isna().sum()

Rk              0
Pk              0
School          0
G_college       0
GS              0
MP_college      0
FG              0
FGA             0
FG%_college     0
2P              0
2PA             0
2P%             0
3P              0
3PA             0
3P%_college    22
FT              0
FTA             0
FT%_college     0
ORB             0
DRB             0
TRB_college     0
AST_college     0
STL             0
BLK             0
TOV             0
PF              0
PTS_college     0
SOS             0
name            0
dtype: int64

In [74]:
df_clean.head()

,Rk,Pk,School,G_college,GS,MP_college,FG,FGA,FG%_college,2P,...,DRB,TRB_college,AST_college,STL,BLK,TOV,PF,PTS_college,SOS,name
1,1,1,Kentucky,37,37,34.8,5.5,11.8,0.461,4.5,...,3.5,4.3,6.5,1.8,0.5,4.0,1.9,16.6,6.82,john wall
5,2,2,Ohio State,101,94,32.8,5.3,10.6,0.502,4.8,...,5.3,6.8,4.1,1.6,0.7,3.5,2.7,15.0,7.86,evan turner
7,3,3,Georgia Tech,36,35,27.5,5.0,8.1,0.611,5.0,...,5.4,8.4,1.0,0.9,2.1,2.5,2.6,12.4,9.02,derrick favors
9,5,5,Kentucky,38,37,23.5,5.4,9.7,0.558,5.4,...,5.8,9.8,1.0,1.0,1.8,2.1,3.2,15.1,6.82,demarcus cousins
15,7,7,Georgetown,65,65,32.6,5.3,9.8,0.543,5.2,...,6.1,8.2,3.2,1.5,1.5,2.9,2.5,14.5,9.26,greg monroe

In [82]:
df_clean.columns

Index(['Rk', 'Pk', 'School', 'G_college', 'GS', 'MP_college', 'FG', 'FGA',
       'FG%_college', '2P', '2PA', '2P%', '3P', '3PA', '3P%_college', 'FT',
       'FTA', 'FT%_college', 'ORB', 'DRB', 'TRB_college', 'AST_college', 'STL',
       'BLK', 'TOV', 'PF', 'PTS_college', 'SOS', 'name'],
      dtype='object')

In [92]:
#convert cols to numeric 
df_clean[['Rk', 'Pk', 'G_college', 'GS', 'MP_college', 'FG', 'FGA',
       'FG%_college', '2P', '2PA', '2P%', '3P', '3PA', '3P%_college', 'FT',
       'FTA', 'FT%_college', 'ORB', 'DRB', 'TRB_college', 'AST_college', 'STL',
       'BLK', 'TOV', 'PF', 'PTS_college', 'SOS']] = df_clean[['Rk', 'Pk', 'G_college', 'GS', 'MP_college', 'FG', 'FGA',
       'FG%_college', '2P', '2PA', '2P%', '3P', '3PA', '3P%_college', 'FT',
       'FTA', 'FT%_college', 'ORB', 'DRB', 'TRB_college', 'AST_college', 'STL',
       'BLK', 'TOV', 'PF', 'PTS_college', 'SOS']].apply(pd.to_numeric)

/Users/jackpiccione/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3636: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [93]:
#create lottery varible 
#if player is a top 14 pick then they are in the lottery 
df_clean['lottery'] = np.where(df_clean['Pk']<=14, True, False)

/Users/jackpiccione/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
#variable description
"""Age -- Player's age on February 1 of the season
G -- Games
MP -- Minutes Played
FG -- Field Goals
FGA -- Field Goal Attempts
3P -- 3-Point Field Goals
3PA -- 3-Point Field Goal Attempts
FT -- Free Throws
FTA -- Free Throw Attempts
ORB -- Offensive Rebounds
TRB -- Total Rebounds
AST -- Assists
STL -- Steals
BLK -- Blocks
TOV -- Turnovers
PF -- Personal Fouls
PTS -- Points
Shooting
FG% -- Field Goal Percentage
3P% -- 3-Point Field Goal Percentage
FT% -- Free Throw Percentage
Per Game
MP -- Minutes Played Per Game
PTS -- Points Per Game
TRB -- Total Rebounds Per Game
AST -- Assists Per Game
lottery -- top 14 pick in draft"""

In [98]:
len(df_clean)

415

In [103]:
#save data as csv
df_clean.to_csv("NBAdraft.csv",index=False)